routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Morilog\Jalali\Jalalian;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('home');

Route::view('/about','about')->name('about');
Route::view('/health-news','health')->name('health.news');

Route::get('/download/voice',function (){
    return response()->download(base_path("about_corona_virus.mpeg"));
})->name('voice.download');

Route::get('/pdf/download',function (){
    return \Illuminate\Support\Facades\Response::download(base_path('corona_recommendation.pdf'));
})->name('pdf.download');

Route::prefix('admin')->name('admin.')->namespace('Auth')->group(function () {
    Route::get('home', 'AdminController@template')->name('home');
    Route::get('login', 'AdminController@showLoginForm')->name('login.view');
    Route::post('login/check', 'AdminController@check')->name('login.check');
    Route::post('logout', 'AdminController@logout')->name('logout');
    Route::get('users/notifications/markAsRead', 'AdminController@markAsRead')->name('users.notifications.markAsRead');
});

Route::prefix('user')->name('user.')->namespace('Auth')->group(function () {
    Route::get('round/{id}', 'UserController@index')->name('round');
    Route::get('join/{round}', 'UserController@create')->name('join');
    Route::get('login/{round?}', 'UserController@login')->name('login');
    Route::post('login/check/{round?}', 'UserController@check')->name('check');
    Route::get('panel', 'UserController@dashboard')->name('dashboard');
    Route::post('logout', 'UserController@logout')->name('logout');
    Route::post('pre/store/{id}', 'UserController@prestore')->name('prestore');
    Route::post('store/{id}', 'UserController@store')->name('store');
    Route::get('pay/start/{round}', 'UserController@pay')->name('pay.start');
    Route::get('pay/result', 'UserController@orderResult')->name('pay.result');
    Route::post('otp/send', 'UserController@otpSend')->name('otp.send');
    Route::post('otp/verify', 'UserController@otpVerify')->name('otp.verify');
    Route::get('all', 'UserController@all')->name('all');
});

Route::prefix('attachment')->name('attachment.')->group(function () {
    Route::post('store/{round_id}/{user_id}', 'AttachmentController@store')->name('store');
    Route::get('download/{round_id}/{user_id}', 'AttachmentController@download')->name('download');
    Route::put('update/{round_id}/{user_id}', 'AttachmentController@update')->name('update');
    Route::delete('destroy/{round_id}/{user_id}', 'AttachmentController@destroy')->name('destroy');
});

Route::delete('round/destroy/multiple', 'RoundController@destroyMultiple')->name('round.destroy.multiple');
Route::delete('round/users/destroy/multiple', 'RoundController@destroyMultiple')->name('round.users.destroy.multiple');
Route::resource('round', 'RoundController');

Route::get('price/set', function () {
    if (\App\Price::count() > 0) {
        $price = \App\Price::first()->price;
    } else {
        $price = null;
    }
    return view('price')->with([
        'price' => $price
    ]);
})->name('price.set')->middleware('auth:admin');
Route::post('price/change', function (\Illuminate\Http\Request $request) {
    \Illuminate\Support\Facades\Validator::make([$request], [
        'price' => 'required|numeric'
    ], [
        'price.required' => 'وارد کردن قیمت الزامی است',
        'price.numeric' => 'قیمت باید به صورت عددی باشد'
    ]);
    if (\App\Price::count() > 0) {
        $price = \App\Price::first();
        $price->price = $request->price;
        $price->save();
    } else {
        \App\Price::create([
            'price' => $request->price
        ]);
    }
    return redirect()->route('admin.home');
})->name('price.change')->middleware('auth:admin');

resources/views/about.blade.php
@extends('layouts.app')

@section('title','آزمایشگاه کیوان - درباره ما')

@section('content')
    <div class="page-wrapper">
        <div class="preloader"></div>
        @include('layouts.header')
        <hr class="p-0 m-0">

        <div class="col-md-11 mx-auto mt-4 text-right iransans-web">
            <h4 class="iransans-web-bold">پروفسور حسین کیوانی</h4>
            <ul class="mt-2" type="disc" dir="rtl">
                <li>
                    متخصص ویروس شناسی بالینی از کانادا
                </li>
                <li>
                    عضو هیأت علمی و استاد دانشگاه علوم پزشکی ایران
                </li>
                <li>
                    مؤسس آزمایشگاه تخصصی ویروس شناسی کیوان
                </li>
                <li>
                    پروفسور حسین کیوانی پس از اخذ دکترای عمومی در سال ۱۳۸۶ از دانشگاه تهران به منظور طی دوره دکترای
                    تخصصی (ph.D) به فرانسه و سپس به کانادا عزیمت نمود. وی در سال ۱۳۷۵ پس از اخذ دکترای تخصصی (ph.D) از
                    دانشگاه شربروک کانادا که، در طول تحصیل وی را "استثنایی" ارزیابی نمود؛ به کشور بازگشت.
                </li>
                <li>
                    پروفسور کیوانی پس از مراجعت به کشور به عنوان عضو هیأت علمی دانشگاه های تهران، علوم پزشکی تهران و
                    علوم
                    پزشکی ایران انجام وظیفه نموده و در حال حاضر استاد تمام دانشکده پزشکی دانشگاه علوم پزشکی ایران می
                    باشد.
                </li>
                <li>
                    با توجه به عدم وجود آزمایشگاه تخصصی ویروس شناسی در کشور و نیاز مبرم به این رشته، دکتر کیوانی اولین
                    آزمایشگاه تخصصی ویروس شناسی را در سال ۱۳۷۹ تأسیس نمود.
                </li>
                <li>
                    از ابتدای تأسیس، کلیه آزمون های مربوط به تشخیص و درمان بیماری های ویروسی با استاندارد مشابه با
                    کشورهای
                    پیشرفته مانند آمریکا و اتحادیه ی اروپا، در این آزمایشگاه انجام می پذیرد و در حال حاضر به عنوان مرجع
                    تخصصی
                    بیماری های ویروسی، مجهز به پیشرفته ترین دستگاه های تخصصی بوده و روزانه پذیرای بیماران بسیاری است.
                </li>
                <li>
                    دکتر کیوانی تاکنون صدها مقاله علمی در مجلات معتبر بین المللی به چاپ رسانده و سخنرانی های زیادی را در
                    کنگره
                    های داخلی و خارجی ارائه نموده است.
                </li>
            </ul>
            <div class="my-3">
            <a href="{{ route('voice.download') }}" style="font-size: 17px" class="py-3">
دانلود فایل صوتی مصاحبه پروفسور حسین کیوانی با رادیو
            </a>
            </div>
            <div class="my-3">
                <a href="https://www.researchgate.net/profile/Hossein_Keyvani" style="font-size: 17px" class="py-3">
                    آشنایی و تحقیقات بیشتر
                </a>
            </div>
        </div>
        <hr>
        <div class="col-md-11 mx-auto mt-4 mb-5 text-right iransans-web">
            <h4 class="iransans-web-bold">معرفی آزمایشگاه کیوان</h4>
            <ul class="mt-2" type="disc" dir="rtl">
                <li>
                    آزمایشگاه تخصصی ویروس شناسی کیوان در سال ۱۳۷۹ با هدف ارائه خدمات تشخیصی، تخصصی و فوق تخصصی در
                    حوزه ی ویروس شناسی به بیماران و پزشکان توسط پروفسور حسین کیوانی تاسیس شد.
                </li>
                <li>
                    از آنجایی که تشخیص صحیح بیماری ها و حتی گزارش صحیح نتایج آزمایشات مستلزم همکاری و ارتباط تنگانگ
                    آزمایشگاه و پزشک معالج است، در این راستا ما دست تمامی پزشکان محترم را به گرمی می فشاریم و از تمام داشته
                    های علمی و تکنیکی خود در این جهت دریغ نمی کنیم.
                </li>
                <li>
                    ما به همراه پزشکان تلاش می کنیم تا بیماری بیماران را تشخیص دهیم، برای سوالات موجود جوابی یافته، پیشرفت
                    بیماری یا بهبودی را ارزیابی کنیم، سلامت افراد سالم را تایید نماییم و در صورت نیاز آموزش دهیم و از ایجاد عوارض
                    جلوگیری کنیم.
                </li>
                <li>
                    همچنین در طی سالها تلاش نموده ایم با کارگیری و گلچین نمودن بهترین دستگاه های تمام اتوماتیک آزمایشگاهی از
                    معروف ترین کمپانی های جهان که از کشور های اروپایی و آمریکا وارد کشور شده است و استفاده از کیت های
                    انحصاری هر دستگاه که توسط شرکت سازنده دستگاه تولید می گردد سعی نموده ایم تا با بالا بردن کیفیت در حد
                    امکان رضایت پزشکان و بیماران را جلب نماید.
                </li>
                <li>
                    این آزمایشگاه به عنوان اولین و تنها آزمایشگاهی که از دستگاه Amplicore Cobas جهت انجام تست Quantitative
                    ویروس های HCV ,HBV , HIV استفاده می کند در میهن عزیزمان شناخته شده است.
                </li>
                <li>
                    هدف ما استفاده از جدید ترین تکنولوژی های روز دنیا و امکانات الکترونیک است تا خدمات خود را صحیح، دقیق، سریع
                    و با کمترین هزینه ارائه نماییم. در این آزمایشگاه مراجعه کننده اولین اولویت است و سعی می شود تا تمامی آزمایش
                    ها مطابق به روزترین استاندارد های بین المللی و کشوری با رعایت استاندارد های کنترل کیفی انجام شوند.
                </li>
                <li>
                    حال؛ با توجه به شیوع ویروس کرونا (COVID-19) در واپسین روزهای سال ۱۳۹۸ در کشور عزیزمان، آزمایشگاه
                    تخصصی ویروس شناسی کیوان توانست با استعانت از خداوند متعال و با مدیریت بهینه منابع و تالش شبانه روزی
                    پرسنل و مسئولین آزمایشگاه، کمک شایانی در تشخیص بیماری هم میهنان عزیزمان نموده و سهم به سزایی در شروع
                    درمان ایشان و جلوگیری از شیوع بیشتر این بیماری داشته باشد.
                </li>
            </ul>
        </div>
    </div>
    @include('footer')
@endsection

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('title',$user->name.'پنل کاربر-')

@section('content')
    @include('layouts.header')
    <hr class="m-0 p-0">
    <div class="col-md-8 col-12 mx-auto text-right my-5 iransans-web">
        <h3 class="mr-1">{{ $user->name }}</h3>
        @php $attachments = $user->attachments @endphp
        @if(count($attachments))
            <ul class="list-group list-group-flush">
                <li class="list-group-item list-group-item-secondary">
                    نتیجه آزمایشات
                </li>
                @foreach($attachments as $attachment)
                    @php $round = $attachment->round @endphp
                    <li class="list-group-item">
                        <a href="{{ route('attachment.download' , ['round_id' => $round->id , 'user_id' => $attachment->user->id])  }}" class="text-secondary">
                            <span>{{ 'نتیجه آزمایش روز '.toFaDigits(\Morilog\Jalali\Jalalian::forge($round->date)->format('%A, %d %B %y').' ساعت '.$round->end.' - '.$round->start) }}</span>
                            <span class="icon icon-file mx-2 font-xl"></span>
                        </a>
                    </li>
                @endforeach
            </ul>
        @else
            <div class="alert alert-info" dir="rtl">
                نتیجه آزمایشی برای شما ثبت نشده است.
            </div>
        @endif
    </div>
@endsection

resources/views/footer.blade.php
<footer id="contact-us" class="main-footer" style="background-image:url(/images/zbackground/7.jpg)">

    <div class="container">

        <!--Widgets Section-->
        <div class="widgets-section">
            <div class="row">

                <!-- Logo Widget-->
                <div class="footer-column col-lg-6 col-md-6">
                    <p class="text text-justify">
                        آزمایشگاه کیوان به دلیل ارائه خدماتی با کیفیت بالا، با
                        مؤسسات دولتی و خصوصی و مراکز آموزش عالی در
                        حال همکاری و در طرحهای تحقیقاتی بسیاری شرکت
                        می‌نماید. این آزمایشگاه تست‌های اورژانس روی
                        نمونه‌های دریافتی را ظرف مدت ۲۴ ساعت پس از
                        دریافت نمونه، آماده و نتایج را اعلام می‌نماید.
                    </p>
                </div>
                <div class="footer-column col-lg-6 col-md-6">
                    <div class="footer-widget logo-widget">
                        <div class="logo">
                            <a href="#"><img src="/images/zfooter-logo-a.png" alt=""/></a>
                        </div>
                        <ul class="list-style-two">
                            <li><a href="#map-location"><span
                                            class="icon flaticon-map-pin-marked"></span>تهران، خیابان شهید بهشتی (عباس‌آباد)، بعد از سینما آزادی، به طرف خیابان ولیعصر، پلاک ۴۹۸ طبقه همکف</a></li>
                            <li><a href="#"><span class="icon flaticon-phone"></span>۰۲۱-۸۸۷۰۶۵۵۶ ۰۲۱-۸۸۷۱۲۸۳۵ ۰۲۱-۸۸۷۱۵۳۵۰ ۰۲۱-۸۸۷۰۹۵۱۳ ۰۲۱-۸۸۱۰۴۸۹۳ ۰۲۱-۸۸۱۰۴۹۵۴</a>
                            </li>
                            <li><a href="mailto:info@keyvanlabtest.ir"><span class="icon flaticon-mail"></span>info@keyvanlabtest.ir</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Footer Bottom -->
    <div class="footer-bottom">
        <div class="container">
            <div class="clearfix">

                <div class="pull-right ">
                    <!-- Copyright -->
                    <p class="copyright">
                        <span>&copy; 1398 تمامی حقوق محفوظ است.</span>
                        {{--<a href="http://virtopia.ir">طراحی و اجرا :--}}
                            {{--<img src="{{ asset('images/virtopia.png') }}" style="width: 200px;height: 100px">--}}
                        {{--</a>--}}
                    </p>
                </div>

                <div class="pull-left">
                    <ul class="social-box">
                        <li class="messanger"><a href="https://keyvanlab.com/"><span class="icon flaticon-messenger"></span>
                                آزمایشگاه تخصصی ویروس شناسی کیوان</a></li>
                        <li class="facebook"><a href="https://www.facebook.com/keyvan.lab.92" class="icon icon-facebook"></a></li>
                        <li class="linkedin"><a href="https://www.linkedin.com/in/keyvan-lab-74a912184/" class="icon icon-linkedin"></a></li>
                        <li class="instagram"><a href="https://www.instagram.com/keyvanlabtest" class="icon icon-instagram"></a></li>
                    </ul>
                </div>

            </div>
        </div>
    </div>

</footer>

resources/views/price.blade.php
@extends('layouts.admin.template')

@section('title','تعیین هزینه ثبت نام')

@section('content')
    <div class="col-md-4 col-sm-7 col-12 mx-auto iransans-web">
        <form class="form" method="post" action="{{ route('price.change') }}">
            {{ csrf_field() }}
            <div class="form-group text-right">
                <label for="price" dir="rtl">قیمت:<span class="font-s">(تومان)</span></label>
                <input type="text" id="price" name="price" class="form-control" value="{{ $price ?: null }}" autocomplete="off" placeholder="هزینه آزمایش را بر حسب تومان وارد کنید" dir="rtl">
            </div>
            <div class="form-group text-left">
                <input type="submit" class="btn btn-primary" value="ثبت">
            </div>
        </form>
    </div>
@endsection

resources/views/table.blade.php
<div class="col-md-10 col-11 mx-auto my-md-5 my-3">
    <div class="your-class">
        @for($i=0;$i<14;$i++)
            <div>
                <div class="box box-header">
                    @php $carbon_date = \Carbon\Carbon::now()->add('day',$i); @endphp
                    @php $date = \Morilog\Jalali\Jalalian::forge($carbon_date); @endphp
                    <h6 class="box-title">{{ $date->format('%A') }}</h6>
                    <p class="box-date">{{ toFaDigits($date->format('%d %B %Y')) }}</p>
                    @php $rounds = \App\Round::where('date' , $carbon_date->toDateString())->get();
                        $rounds=collect($rounds)->sort(function ($a,$b){
         $int_a = intval(str_replace(':','',$a['start']).str_replace(':','',$a['end']));
         $int_b = intval(str_replace(':','',$b['start']).str_replace(':','',$b['end']));
         if ($int_a == $int_b){
             return 0;
         }
         return ($int_a < $int_b) ? -1 : 1;
     });
                    @endphp
                </div>
                @forelse($rounds as $round)
                    <a href="{{ $round->remaining > 0 ? (auth('web')->check() ? route('user.pay.start',$round->id) : route('user.join',$round->id)) : '' }}"
                       style="text-decoration: none;cursor: {{ $round->remaining > 0 ? 'pointer' : 'not-allowed' }}">
                        <div class="box box-content">
                            <p class="p-2">{{ toFaDigits($round->end.' - '.$round->start) }}</p>
                            <p class="box-date">
                                <span class="badge badge-primary">ظرفیت</span>
                                <strong>{{ toFaDigits($round->capacity) }}</strong>
                            </p>
                            <p class="box-date">
                                <span class="badge badge-warning">مانده</span>
                                <strong>{{ toFaDigits($round->remaining) }}</strong>
                            </p>
                        </div>
                    </a>
                @empty
                    <p class="iransans-web font-s text-center" dir="rtl">
                        سانسی
                        برای امروز
                        تعریف
                        نشده است.
                    </p>
                @endforelse
            </div>
        @endfor
    </div>
</div>

resources/views/userall.blade.php
@extends('layouts.admin.template')

@section('title','سانس ها')

@section('style')
    <link type="text/css" rel="stylesheet" href="{{ asset('style/index/flaticon.css') }}">
    <style>
        .table th {
            font-size: 13px;
        }

        .box {
            text-align: right;
            direction: rtl;
            border: 1px solid rgb(31, 186, 180);
            border-radius: 5px;
            line-height: 1.75;
            padding: .75rem;
            background-color: rgb(213, 251, 245);
            color: rgb(1, 104, 152);
            font-size: 14px;
            font-family: iransans_web;
            margin: 1rem 0;
        }

        .box-header, .box-header > div {
            display: flex;
            flex-direction: row;
            justify-content: flex-start;
            align-items: center;
            flex-wrap: wrap;
        }

        .box-divider {
            margin: 1rem 0;
            width: 100%;
            height: 1.5px;
            background-color: rgb(31, 186, 180);
        }
    </style>
@endsection

@section('content')
    @include('layouts.alert')

    <div class="col-md-10 col-12 mx-auto my-5 iransans-web-light text-right">
        <div class="d-flex flex-row justify-content-between align-items-end mb-md-4">
            <a href="{{ route('admin.home') }}" data-md-tooltip="بازگشت"
               class="shortcut-link shadow-sm material-icons md-tooltip md-tooltip--top">
                <img src="{{ asset('icons1/return.png') }}">
            </a>
            <div class="col-md-4 pr-0">
                <h5>کاربران ثبت شده</h5>
                <div class="input-group input-group-sm rounded">
                    <div class="input-group-append bg-white border border-right-0 rounded-left">
                        <img src="{{ asset('icons1/search.png') }}" width="20" height="20" class="rounded mt-1 mx-1">
                    </div>
                    <input class="form-control border-left-0" type="search" placeholder="جست و جو" aria-label="Search"
                           dir="rtl">
                </div>
            </div>
        </div>
        @if(count($users))
            <table id="example1" class="table rounded bg-white text-dark rounded">
                <thead>
                <tr dir="rtl" class="ml-auto">
                    {{--<td class="border-0"></td>--}}
                    {{--<td class="border-0"></td>--}}
                    {{--<td class="border-0"></td>--}}
                    {{--<td class="border-0"></td>--}}
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0 d-flex align-items-center">
                        <input type="checkbox" class="toggle" value="1">
                        <span class="fas fa-chevron-down font-s font-weight-bold text-dark mr-2"
                              data-toggle="dropdown"></span>
                        <ul class="dropdown-menu dropdown-menu-right p-1 text-right">
                            <li>
                                <form id="round_multiple" method="post"
                                      action="{{ route('round.users.destroy.multiple') }}" class="d-none">
                                    {{ csrf_field() }}
                                    {{ method_field('delete') }}
                                </form>
                                <a onclick="$(this).addClass('active');$('.alert-container').fadeIn();"
                                   class="delete text-dark" href="#">حذف</a>
                            </li>
                        </ul>
                    </td>
                </tr>
                <tr class="bg-light">
                    {{--<th class="p-2" style="width: 35px"></th>--}}
                    {{--<th class="p-2" style="width: 35px"></th>--}}
                    {{--<th class="p-2" style="width: 35px"></th>--}}
                    {{--<th class="p-2">نتیجه آزمایش</th>--}}
                    <th class="p-2">آدرس</th>
                    <th class="p-2">سن</th>
                    <th class="p-2">کد ملی</th>
                    <th class="p-2">شماره تماس</th>
                    <th class="p-2">
                        <div class="d-flex justify-content-end align-items-center">
                            <span class="mr-1">نام پدر</span>
                            <span class="fas fa-sort text-lighter"></span>
                        </div>
                    </th>
                    <th class="p-2">
                        <div class="d-flex justify-content-end align-items-center">
                            <span class="mr-1">نام و نام خانوادگی</span>
                            <span class="fas fa-sort text-lighter"></span>
                        </div>
                    </th>
                    <th class="p-2"></th>
                </tr>
                </thead>
                <tbody>
                @php $index=1; @endphp
                {{--@php $users=$round->users @endphp--}}
                @foreach($users as $user)
                    <tr>
                        {{--<td>--}}
                        {{--<form method="post" action="{{ route('attachment.destroy' , ['round_id' => $round->id , 'user_id' => $user->id]) }}" class="d-none">--}}
                        {{--{{ csrf_field() }}--}}
                        {{--{{ method_field('delete') }}--}}
                        {{--</form>--}}
                        {{--<a onclick="$(this).addClass('active');$('.alert-container').fadeIn();" href="#"--}}
                        {{--class="material-icons md-tooltip md-tooltip--top delete" data-md-tooltip="حذف نتیجه">--}}
                        {{--<img src="{{ asset('icons1/trash.png') }}" width="20" height="20">--}}
                        {{--</a>--}}
                        {{--</td>--}}
                        {{--<td>--}}
                        {{--<form method="post" action="{{ route('attachment.update',['round_id' => $round->id , 'user_id' => $user->id]) }}"--}}
                        {{--enctype="multipart/form-data" class="d-none">--}}
                        {{--{{ csrf_field() }}--}}
                        {{--{{ method_field('PUT') }}--}}
                        {{--<input type="file" name="file">--}}
                        {{--</form>--}}
                        {{--<a class="update material-icons md-tooltip md-tooltip--top" data-md-tooltip="ویرایش نتیجه">--}}
                        {{--<img src="{{ asset('icons1/edit.png') }}" width="20" height="20">--}}
                        {{--</a>--}}
                        {{--</td>--}}
                        {{--@if(\App\Attachment::where('round_id',$round->id)->where('user_id',$user->id)->first())--}}
                        {{--<td><a href="{{ route('attachment.download' , ['round_id' => $round->id , 'user_id' => $user->id]) }}"--}}
                        {{--class="material-icons md-tooltip md-tooltip--top" data-md-tooltip="مشاهده نتیجه">--}}
                        {{--<img src="{{ asset('icons1/eye.png') }}" width="20" height="20">--}}
                        {{--</a></td>--}}
                        {{--@else--}}
                        {{--<td>--}}
                        {{--<form method="post" action="{{ route('attachment.store',['round_id' => $round->id , 'user_id' => $user->id]) }}"--}}
                        {{--enctype="multipart/form-data" class="d-none">--}}
                        {{--{{ csrf_field() }}--}}
                        {{--<input type="file" name="file">--}}
                        {{--</form>--}}
                        {{--<a class="upload material-icons md-tooltip md-tooltip--top"--}}
                        {{--data-md-tooltip="آپلود نتیجه">--}}
                        {{--<img src="{{ asset('icons1/upload.png') }}" width="20" height="20">--}}
                        {{--</a></td>--}}
                        {{--@endif--}}
                        {{--<td class="text-dark">--}}
                        {{--<span class="badge badge-{{ \App\Attachment::where('round_id',$round->id)->where('user_id',$user->id)->first() ? 'success' : 'warning' }}">{{ \App\Attachment::where('round_id',$round->id)->where('user_id',$user->id)->first() ? 'ارسال شده' : 'در انتظار' }}</span>--}}
                        {{--</td>--}}
                        <td class="text-dark font-s">{{ toFaDigits($user->address) }}</td>
                        <td class="text-dark">{{ toFaDigits($user->age) }}</td>
                        <td class="text-dark">{{ toFaDigits($user->melli_code) }}</td>
                        <td class="text-dark">{{ toFaDigits($user->phone) }}</td>
                        <td class="text-dark" dir="rtl">{{ toFaDigits($user->parent) }}</td>
                        <td class="text-dark">{{ toFaDigits($user->name) }}</td>
                        <td style="width: 15px">
                            <input type="checkbox" name="deletable[]" value="{{ $user->id }}">
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <div class="alert alert-primary text-right my-3" dir="rtl">
                این سانس توسط کسی رزرو نشده است.
            </div>
        @endif
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $("a.upload , a.update").on("click", function () {
                $(this).prev().find('input[type=\'file\']').click();
            });

            $("input[type='file']").on("change", function () {
                $(this).parent().submit();
            });
            $("input[type='search']").on("keyup", function () {
                var value = $(this).val();
                $("table tbody tr").each(function (index) {
                    var $row = $(this);
                    var id = $row.children().eq(4).text()
                    if (id.indexOf(value) !== 0) {
                        $row.hide();
                    } else {
                        $row.show();
                    }
                });
            });
        });
    </script>
@endsection