routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Morilog\Jalali\Jalalian;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('home');

Route::view('/about','about')->name('about');
Route::view('/health-news','health')->name('health.news');

Route::get('/download/voice',function (){
    return response()->download(base_path("about_corona_virus.mpeg"));
})->name('voice.download');

Route::get('/pdf/download',function (){
    return \Illuminate\Support\Facades\Response::download(base_path('corona_recommendation.pdf'));
})->name('pdf.download');

Route::prefix('admin')->name('admin.')->namespace('Auth')->group(function () {
    Route::get('home', 'AdminController@template')->name('home');
    Route::get('login', 'AdminController@showLoginForm')->name('login.view');
    Route::post('login/check', 'AdminController@check')->name('login.check');
    Route::post('logout', 'AdminController@logout')->name('logout');
    Route::get('users/notifications/markAsRead', 'AdminController@markAsRead')->name('users.notifications.markAsRead');
});

Route::prefix('user')->name('user.')->namespace('Auth')->group(function () {
    Route::get('round/{id}', 'UserController@index')->name('round');
    Route::get('join/{round}', 'UserController@create')->name('join');
    Route::get('login/{round?}', 'UserController@login')->name('login');
    Route::post('login/check/{round?}', 'UserController@check')->name('check');
    Route::get('panel', 'UserController@dashboard')->name('dashboard');
    Route::post('logout', 'UserController@logout')->name('logout');
    Route::post('pre/store/{id}', 'UserController@prestore')->name('prestore');
    Route::post('store/{id}', 'UserController@store')->name('store');
    Route::get('pay/start/{round}', 'UserController@pay')->name('pay.start');
    Route::get('pay/result', 'UserController@orderResult')->name('pay.result');
    Route::post('otp/send', 'UserController@otpSend')->name('otp.send');
    Route::post('otp/verify', 'UserController@otpVerify')->name('otp.verify');
    Route::get('all', 'UserController@all')->name('all');
});

Route::prefix('attachment')->name('attachment.')->group(function () {
    Route::post('store/{round_id}/{user_id}', 'AttachmentController@store')->name('store');
    Route::get('download/{round_id}/{user_id}', 'AttachmentController@download')->name('download');
    Route::put('update/{round_id}/{user_id}', 'AttachmentController@update')->name('update');
    Route::delete('destroy/{round_id}/{user_id}', 'AttachmentController@destroy')->name('destroy');
});

Route::delete('round/destroy/multiple', 'RoundController@destroyMultiple')->name('round.destroy.multiple');
Route::delete('round/users/destroy/multiple', 'RoundController@destroyMultiple')->name('round.users.destroy.multiple');
Route::resource('round', 'RoundController');

Route::get('price/set', function () {
    if (\App\Price::count() > 0) {
        $price = \App\Price::first()->price;
    } else {
        $price = null;
    }
    return view('price')->with([
        'price' => $price
    ]);
})->name('price.set')->middleware('auth:admin');
Route::post('price/change', function (\Illuminate\Http\Request $request) {
    \Illuminate\Support\Facades\Validator::make([$request], [
        'price' => 'required|numeric'
    ], [
        'price.required' => 'وارد کردن قیمت الزامی است',
        'price.numeric' => 'قیمت باید به صورت عددی باشد'
    ]);
    if (\App\Price::count() > 0) {
        $price = \App\Price::first();
        $price->price = $request->price;
        $price->save();
    } else {
        \App\Price::create([
            'price' => $request->price
        ]);
    }
    return redirect()->route('admin.home');
})->name('price.change')->middleware('auth:admin');

resources/views/layouts/admin/home.blade.php
@extends('layouts.admin.template')

@section('style')
    <link type="text/css" rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
@endsection

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3 d-lg-block d-none">
                </div>
                {{--<!-- ./col -->--}}
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner text-md-right text-center">
                            <h3>{{ toFaDigits(count(auth('admin')->user()->newMembers())) }}</h3>
                            <p>کاربر جدید</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a href="#" class="small-box-footer" style="visibility: hidden">اطلاعات بیشتر <i class="fa fa-arrow-circle-left"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner text-md-right text-center">
                            <h3>{{ toFaDigits(\App\User::count()) }}</h3>
                            <p>کاربر عضوشده</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person"></i>
                        </div>
                        <a href="{{ route('user.all') }}" class="small-box-footer">اطلاعات بیشتر <i class="fa fa-arrow-circle-left"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner text-md-right text-center">
                            <h3>{{ toFaDigits(\App\Round::count()) }}</h3>
                            <p>سانس</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-ios-body-outline"></i>
                        </div>
                        <a href="{{ route('round.index') }}" class="small-box-footer">اطلاعات بیشتر <i class="fa fa-arrow-circle-left"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>
        </div>
    </section>
@endsection

resources/views/layouts/admin/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-dark" style="background-color: #3c8dbc">

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-3">
        {{--<li class="nav-item">--}}
            {{--<a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i--}}
                        {{--class="fas fa-cogs"></i></a>--}}
        {{--</li>--}}

        <!-- Notifications Dropdown Menu -->
        <li id="registered_users_notification" class="nav-item dropdown">
            @component('layouts.notifications.all' , ['notifications' => auth('admin')->user()->newMembers() ])
                @slot('id') mark_as_read_users @endslot
                @slot('title') عضو جدید @endslot
                @slot('icon') far fa-bell @endslot
                @slot('badge') badge-warning @endslot
            @endcomponent
        {{--</li>--}}

        {{--<!-- Messages Dropdown Menu -->--}}
        {{--<li class="nav-item dropdown">--}}
            {{--@component('layouts.notifications.all' , ['notifications' => auth()->user()->newMessages()])--}}
                {{--@slot('id') mark_as_read_messages @endslot--}}
                {{--@slot('title') پیام جدید @endslot--}}
                {{--@slot('icon')far fa-comments @endslot--}}
                {{--@slot('badge') badge-danger @endslot--}}
            {{--@endcomponent--}}
            {{--<div class="dropdown-menu dropdown-menu-lg dropdown-menu-left">--}}
            {{--<a href="#" class="dropdown-item">--}}
            {{--<!-- Message Start -->--}}
            {{--<div class="media">--}}
            {{--<img src="{{ asset('adminlte/dist/img/user1-128x128.jpg') }}" alt="User Avatar"--}}
            {{--class="img-size-50 mr-3 img-circle">--}}
            {{--<div class="media-body">--}}
            {{--<h3 class="dropdown-item-title">--}}
            {{--Brad Diesel--}}
            {{--<span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>--}}
            {{--</h3>--}}
            {{--<p class="text-sm">Call me whenever you can...</p>--}}
            {{--<p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--<!-- Message End -->--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item">--}}
            {{--<!-- Message Start -->--}}
            {{--<div class="media">--}}
            {{--<img src="{{ asset('adminlte/dist/img/user8-128x128.jpg') }}" alt="User Avatar"--}}
            {{--class="img-size-50 img-circle mr-3">--}}
            {{--<div class="media-body">--}}
            {{--<h3 class="dropdown-item-title">--}}
            {{--John Pierce--}}
            {{--<span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>--}}
            {{--</h3>--}}
            {{--<p class="text-sm">I got your message bro</p>--}}
            {{--<p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--<!-- Message End -->--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item">--}}
            {{--<!-- Message Start -->--}}
            {{--<div class="media">--}}
            {{--<img src="{{ asset('adminlte/dist/img/user3-128x128.jpg') }}" alt="User Avatar"--}}
            {{--class="img-size-50 img-circle mr-3">--}}
            {{--<div class="media-body">--}}
            {{--<h3 class="dropdown-item-title">--}}
            {{--Nora Silvester--}}
            {{--<span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>--}}
            {{--</h3>--}}
            {{--<p class="text-sm">The subject goes here</p>--}}
            {{--<p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--<!-- Message End -->--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item dropdown-footer">See All Messages</a>--}}
            {{--</div>--}}
        </li>
    </ul>

    <!-- SEARCH FORM -->
    {{--<form class="form-inline ml-auto">--}}
    {{--<div class="input-group input-group-sm">--}}
    {{--<div class="input-group-append">--}}
    {{--<button class="btn btn-navbar" type="submit">--}}
    {{--<i class="fas fa-search"></i>--}}
    {{--</button>--}}
    {{--</div>--}}
    {{--<input class="form-control form-control-navbar" type="search" placeholder="جست و جو" aria-label="Search" dir="rtl">--}}
    {{--</div>--}}
    {{--</form>--}}
    <ul class="navbar-nav ml-auto">
        {{--<li class="nav-item d-none d-sm-inline-block">--}}
        {{--<a href="#" class="nav-link">Contact</a>--}}
        {{--</li>--}}
        {{--<li class="nav-item d-none d-sm-inline-block">--}}
        {{--<a href="#" class="nav-link">Home</a>--}}
        {{--</li>--}}
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
</nav>

resources/views/layouts/admin/template.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>پنل ادمین - @yield('title')</title>

    <!-- Font Awesome Icons -->
    <link type="text/css" rel="stylesheet" href="{{ asset('adminlte/plugins/fontawesome-free/css/all.min.css') }}">
    <!-- Theme style -->
    <link type="text/css" rel="stylesheet" href="{{ asset('adminlte/dist/css/adminlte.css') }}">

    <link type="text/css" rel="stylesheet" href="{{ asset('adminlte/dist/css/custom-style.css') }}">

    <link type="text/css" rel="stylesheet" href="{{ asset('style/font.css') }}">

    <link type="text/css" rel="stylesheet" href="{{ asset('style/tooltip.css') }}">
    {{--<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">--}}

    <style>
        #blueimp-gallery {
            position: fixed;
            z-index: 999999;
            bottom: 0;
            left: 0;
            right: 0;
            top: 0;
            background-color: rgba(54, 54, 54, 0.84);
        }

        #blueimp-gallery > img {
            position: absolute;
            max-width: 100%;
            max-height: 100%;
            top: 50%;
            left: 50%;
            -webkit-transform: translate(-50%, -50%);
            -moz-transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            -o-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
        }

        #blueimp-gallery .close {
            position: absolute;
            top: 5%;
            right: 5%;
            color: white;
            font-size: 6rem;
            font-weight: bold;
        }

        .shortcut-link {
            /*width: 75px;*/
            /*height: 75px;*/
            margin: .5rem;
            padding: .5rem;
            border-radius: .25rem;
            -webkit-transition: ease .25s;
            -moz-transition: ease .25s;
            -ms-transition: ease .25s;
            -o-transition: ease .25s;
            transition: ease .25s;
        }

        .control-sidebar label {
            font-family: vazir-light !important;
            font-weight: lighter !important;
            font-size: 14px;
        }
    </style>

    @yield('style')

</head>
<body class="hold-transition sidebar-mini">

<div class="wrapper">
    <!-- Navbar -->
@include('layouts.admin.navbar')
<!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{{ route('admin.home') }}" class="brand-link d-flex flex-row-reverse" style="background-color: #367fa9">
            <img src="https://keyvanlab.com/HCMS-assets/img/fav.ico" alt="AdminLTE Logo"
                 class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light text-center m-0">آزمایشگاه کیوان</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 pr-3 d-flex">
                <div class="info">
                    <a href="#" class="d-block">{{ auth('admin')->user()->email }}</a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column text-right iransans-web" data-widget="treeview"
                    role="menu"
                    data-accordion="false">
                    <li class="nav-item">
                        <a href="{{ route('admin.home') }}" class="nav-link {{ strpos(\Illuminate\Support\Facades\Route::currentRouteName(),'admin.') !== false ? 'active' : '' }}">
                            <i class="nav-icon fas fa-home"></i>
                            <p>داشبورد</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('round.index') }}" class="nav-link {{ strpos(\Illuminate\Support\Facades\Route::currentRouteName(),'round.') !== false ? 'active' : '' }}">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>سانس</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('price.set') }}" class="nav-link {{ strpos(\Illuminate\Support\Facades\Route::currentRouteName(),'price.') !== false ? 'active' : '' }}">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>هزینه</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <form id="admin_logout_form" method="post" action="{{ route('admin.logout') }}" class="d-none">
                            {{ csrf_field() }}
                        </form>
                        <a href="#" onclick="$('#admin_logout_form').submit();" class="nav-link">
                            <i class="nav-icon fas fa-sign-out-alt"></i>
                            <p>خروج</p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper text-center pb-5">
        <div class="col-12 d-flex flex-row justify-content-between align-items-center px-md-5 px-2 pt-1">
            <p></p>
            <ol class="breadcrumb" style="background-color: transparent">
            </ol>
        </div>
        @yield('content')
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    {{--<aside class="control-sidebar control-sidebar-dark iransans-web">--}}
        {{--<!-- Control sidebar content goes here -->--}}
        {{--<div class="col-12 text-right pr-3 pt-3" dir="rtl">--}}
            {{--به زودی در این قسمت تنظیمات پنل ادمین قرار داده میشود.--}}
        {{--</div>--}}
    {{--</aside>--}}
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{ asset('adminlte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
{{--<!-- AdminLTE App -->--}}
<script src="{{ asset('adminlte/dist/js/adminlte.min.js') }}"></script>

<script>
    $(document).ready(function () {

        var toggle = 0;

        $("#mark_as_read_users").click(function () {
            $.ajax({
                method: "GET",
                url: "{{ route('admin.users.notifications.markAsRead') }}",
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
        });
        $(".shortcut-link").hover(function () {
            $(this).toggleClass("shadow shadow-sm");
        }, function () {
            $(this).toggleClass("shadow shadow-sm");
        });

        $("#fixed_navbar_toggle_checkbox").on("change", function () {
            $("nav.main-header").toggleClass("fixed-top");
        });
    });
</script>

@yield('script')

</body>
</html>