routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Morilog\Jalali\Jalalian;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('home');

Route::view('/about','about')->name('about');
Route::view('/health-news','health')->name('health.news');

Route::get('/download/voice',function (){
    return response()->download(base_path("about_corona_virus.mpeg"));
})->name('voice.download');

Route::get('/pdf/download',function (){
    return \Illuminate\Support\Facades\Response::download(base_path('corona_recommendation.pdf'));
})->name('pdf.download');

Route::prefix('admin')->name('admin.')->namespace('Auth')->group(function () {
    Route::get('home', 'AdminController@template')->name('home');
    Route::get('login', 'AdminController@showLoginForm')->name('login.view');
    Route::post('login/check', 'AdminController@check')->name('login.check');
    Route::post('logout', 'AdminController@logout')->name('logout');
    Route::get('users/notifications/markAsRead', 'AdminController@markAsRead')->name('users.notifications.markAsRead');
});

Route::prefix('user')->name('user.')->namespace('Auth')->group(function () {
    Route::get('round/{id}', 'UserController@index')->name('round');
    Route::get('join/{round}', 'UserController@create')->name('join');
    Route::get('login/{round?}', 'UserController@login')->name('login');
    Route::post('login/check/{round?}', 'UserController@check')->name('check');
    Route::get('panel', 'UserController@dashboard')->name('dashboard');
    Route::post('logout', 'UserController@logout')->name('logout');
    Route::post('pre/store/{id}', 'UserController@prestore')->name('prestore');
    Route::post('store/{id}', 'UserController@store')->name('store');
    Route::get('pay/start/{round}', 'UserController@pay')->name('pay.start');
    Route::get('pay/result', 'UserController@orderResult')->name('pay.result');
    Route::post('otp/send', 'UserController@otpSend')->name('otp.send');
    Route::post('otp/verify', 'UserController@otpVerify')->name('otp.verify');
    Route::get('all', 'UserController@all')->name('all');
});

Route::prefix('attachment')->name('attachment.')->group(function () {
    Route::post('store/{round_id}/{user_id}', 'AttachmentController@store')->name('store');
    Route::get('download/{round_id}/{user_id}', 'AttachmentController@download')->name('download');
    Route::put('update/{round_id}/{user_id}', 'AttachmentController@update')->name('update');
    Route::delete('destroy/{round_id}/{user_id}', 'AttachmentController@destroy')->name('destroy');
});

Route::delete('round/destroy/multiple', 'RoundController@destroyMultiple')->name('round.destroy.multiple');
Route::delete('round/users/destroy/multiple', 'RoundController@destroyMultiple')->name('round.users.destroy.multiple');
Route::resource('round', 'RoundController');

Route::get('price/set', function () {
    if (\App\Price::count() > 0) {
        $price = \App\Price::first()->price;
    } else {
        $price = null;
    }
    return view('price')->with([
        'price' => $price
    ]);
})->name('price.set')->middleware('auth:admin');
Route::post('price/change', function (\Illuminate\Http\Request $request) {
    \Illuminate\Support\Facades\Validator::make([$request], [
        'price' => 'required|numeric'
    ], [
        'price.required' => 'وارد کردن قیمت الزامی است',
        'price.numeric' => 'قیمت باید به صورت عددی باشد'
    ]);
    if (\App\Price::count() > 0) {
        $price = \App\Price::first();
        $price->price = $request->price;
        $price->save();
    } else {
        \App\Price::create([
            'price' => $request->price
        ]);
    }
    return redirect()->route('admin.home');
})->name('price.change')->middleware('auth:admin');

resources/views/layouts/alert.blade.php
    <style>
    .alert-container{
        display: none;
        position: fixed;
        top: 0;
        left:0;
        right : 0;
        bottom: 0;
        background-color: rgba(62, 62, 62, 0.81);
        z-index: 9999999999;
    }

    .alert-body{
        position: absolute;
        left: 50%;
        top: 50%;
        -webkit-transform: translate(-50%, -50%);
        -moz-transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        -o-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
        background-color: #efefef;
        border-radius: 5px;
        box-shadow: 0px 0px 5px rgba(160, 160, 160, 0.5);
        font-family: iransans_web_light;
        padding: 1rem;
        text-align: right;
        font-size: 14px;
    }

    .alert-title{
        color : #252525;
        font-family: iransans_web_medium;
    }
</style>

<div class="alert-container">
    <div class="alert-body">
        <h6 class="alert-title">
        </h6>
        <p class="alert-text">
            {{--{{ $txt }}--}}
            آیا از حذف این سانس مطمئن هستید ؟
        </p>
        <a href="#" onclick="$(this).parents('.alert-container').fadeOut('fast');$('a.delete.active').removeClass('active')" class="alert-nok btn btn-sm btn-default text-danger">خیر</a>
        <a href="#" onclick="$(this).parents('.alert-container').fadeOut('fast');$('a.delete.active').prev('form').submit();" class="alert-ok btn btn-sm btn-default text-primary">بله</a>
    </div>
</div>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>آزمایشگاه تخصصی ویروس شناسی کیوان - @yield('title')</title>
    <link rel="icon" type="image/ico" href="{{ asset('images/logo.jfif') }}">
{{----}}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
{{--    <link href="{{ asset('style/index/bootstrap.css') }}" rel="stylesheet">--}}
    <link href="{{ asset('style/index/jquery-ui.css') }}" rel="stylesheet">
    <link href="{{ asset('style/index/icomoon-icons.css')  }}" rel="stylesheet">
    <link href="{{ asset('style/index/animate.css') }}" rel="stylesheet">
    <link href="{{ asset('style/index/flaticon.css') }}" rel="stylesheet">
    <link href="{{ asset('style/index/owl.css') }}" rel="stylesheet">
    <link href="{{ asset('style/index/animation.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('style/index/magnific-popup.css') }}">
{{--    <link href="{{ asset('style/index/jquery.fancybox.min.css') }}" rel="stylesheet">--}}
{{--    <link href="{{ asset('style/index/jquery.mCustomScrollbar.min.css') }}" rel="stylesheet">--}}
    <link href="{{ asset('style/index/menu.css') }}" rel="stylesheet">
    <link href="{{ asset('style/index/style.css') }}" rel="stylesheet">
    <link href="{{ asset('style/index/responsive.css') }}" rel="stylesheet">

    <link type="text/css" rel="stylesheet" href="{{ asset('style/font.css') }}">

    <style>
        #back-to-admin-panel{
            position: fixed;
            text-align: center;
            top: 2rem;
            left: 2rem;
            /*width: 5rem;*/
            /*height: 3rem;*/
            background-color: #0E9A00;
            color : #eee ;
            padding: 2.5rem 1.8rem 3rem 1.8rem;
            border-radius: 50%;
            box-shadow: 0 0 4px rgba(37, 37, 37, 0.71);
            z-index: 999999999;
            text-decoration:none;
        }


        a.btn-custom {
            color: #fff;
            background-color: #cb1313;
            border-radius: 20px;
            padding: .5rem 1.75rem !important;
            text-decoration: none;

            -webkit-transition: background-color .3s;
            -moz-transition: background-color .3s;
            -ms-transition: background-color .3s;
            -o-transition: background-color .3s;
            transition: background-color .3s;
        }

        a.btn-custom:hover {
            color: #fff;
            text-decoration: none;
            background-color: rgb(227, 80, 65);
        }

    </style>
    @yield('style')

</head>
<body class="iransans-web">

@include('layouts.modal')
<main>
    @yield('content','default content')
</main>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="{{ asset('js/index/jquery-ui.js') }}"></script>
<script src="{{ asset('js/index/owl.js') }}"></script>
<script src="{{ asset('js/index/paroller.js') }}"></script>
<script src="{{ asset('js/index/wow.js') }}"></script>
<script src="{{ asset('js/index/main.js') }}"></script>
<script src="{{ asset('js/index/script.js') }}"></script>
<script>
    $(document).ready(function () {
        $("#myModal").modal();
    });
</script>
@yield('script')
</body>
</html>

resources/views/layouts/header.blade.php
<header class="elementskit-header main-header">
    <!-- Header Upper -->
    <div class="header-upper">
        <!-- xs-container -->
        <div class="container">
            <div class="xs-navbar clearfix">

                <div class="logo-outer">
                    <div class="logo"><a href="{{ route('home') }}"><img
                                    src="{{ asset('images/logo.png') }}" class="img-fluid"
                                    style="height: 60px " alt=""
                                    title=""></a>
                    </div>
                </div>

                <nav class="elementskit-navbar">
                    <button class=" elementskit-menu-toggler xs-bold-menu">

                        <div class="xs-gradient-group">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                        <span>
									منو
								</span>
                    </button>
                    <!-- end humberger -->

                    <!-- start menu container -->
                    <div class="elementskit-menu-container elementskit-menu-offcanvas-elements">

                        <!-- start menu item list -->
                        <ul class="elementskit-navbar-nav nav-alignment-dynamic">
                            <li><a href="{{ route('home') }}" class="mx-2">خانه</a></li>
                            @if(\Illuminate\Support\Facades\Route::currentRouteName() == 'home')
                                {{--<li><a href="#featured-section" class="mx-2">ویژگی ها و امکانات</a></li>--}}
                                <li><a href="#rounds-section" class="mx-2">سانس‌ها</a></li>
                            @endif
                            @if(!auth()->check())
                                <li><a href="{{ route('user.login') }}" class="mx-2">جواب‌دهی آنلاین</a></li>
                            @else
                                <li class="elementskit-dropdown-has">
                                    <a href="#">{{ auth()->user()->name }}</a>
                                    <ul class="elementskit-dropdown elementskit-submenu-panel">
                                        <li class="{{ \Illuminate\Support\Facades\Route::currentRouteName()=='user.dashboard' ? 'active' : ''  }}"><a href="{{ route('user.dashboard') }}">پنل کاربری</a></li>
                                        <form id="logout_form" method="post" action="{{ route('user.logout') }}"
                                              class="d-none">
                                            {{ csrf_field() }}
                                        </form>
                                        <li><a onclick="$('#logout_form').submit()" class="mx-2">خروج</a></li>
                                    </ul>
                                </li>
                            @endif
                            <li><a href="{{ route('health.news') }}" class="mx-2">تازه های سلامت</a></li>
                            <li><a href="{{ route('about') }}" class="mx-2">درباره ما</a></li>
                            <li><a href="#contact-us" class="mx-2">تماس با ما</a></li>
                        </ul>

                        <!-- start menu logo and close button (for mobile offcanvas menu) -->
                        <div class="elementskit-nav-identity-panel">
                            <h1 class="elementskit-site-title">
                                <a href="#" class="elementskit-nav-logo">منو</a>
                            </h1>
                            <button class="elementskit-menu-close elementskit-menu-toggler" type="button"><i
                                        class="icon icon-cross"></i></button>
                        </div>
                        <!-- end menu logo and close button -->

                    </div>
                    <!-- end menu container -->

                    <!-- start offcanvas overlay -->
                    <div class="elementskit-menu-overlay elementskit-menu-offcanvas-elements elementskit-menu-toggler">
                    </div>
                    <!-- end offcanvas overlay -->
                    <!-- ---------------------------------------
                            // god menu markup end
                        ---------------------------------------- -->

                </nav>
                {{--<ul class="xs-menu-tools">--}}
                {{--<li>--}}
                {{--<a href="#modal-popup-2" class="navsearch-button xs-modal-popup"><i--}}
                {{--class="icon icon-search"></i></a>--}}
                {{--</li>--}}
                {{--</ul>--}}
            </div>
        </div>
    </div>
    <!-- .container END -->
</header>

resources/views/layouts/modal.blade.php
@if($title = \Illuminate\Support\Facades\Session::get('flash'))
    <div class="modal fade iransans-web-light" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-right" style="font-size: 15px" dir="rtl">
                {{ toFaDigits($title) }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-danger mr-auto" data-dismiss="modal">باشد</button>
                </div>
            </div>
        </div>
    </div>
@endif

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-md d-flex flex-wrap flex-row-reverse {{ \Illuminate\Support\Facades\Route::currentRouteName() == 'home' ? '' : '-dark' }}">
    <a href="{{ route('home') }}" class="navbar-brand ml-3 my-3 mr-0"><img src="{{ asset('icons1/logo.png') }}"></a>
    {{--<div class="elementor-flex-right">--}}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <img src="{{ asset('icons1/toggle'.(\Illuminate\Support\Facades\Route::currentRouteName() == 'home' ? '' : '-dark').'.png') }}"
             width="28" height="28">
    </button>

    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <div class="w-100 d-flex flex-lg-row flex-column-reverse flex-wrap justify-content-between align-items-lg-center align-items-end">
            <ul class="navbar-nav d-md-block d-none text-right">
                <li class="navbar-text m-lg-2 m-1">
                    @if(auth()->check())
                        <a href="{{ route(auth()->user()->isAdmin() ? 'admin.home' :'home') }}" class="btn-custom">پنل کاربری</a>
                    @else
                        <a href="{{ route('join-member.view') }}" class="btn-custom">عضو شوید</a>
                    @endif
                </li>
                <li class="navbar-text m-lg-2 m-1">
                    <span>۰۹۰۵۷۵۰۷۹۶۹</span>
                    <img src="{{ asset('icons1/phone.png') }}">
                </li>
                <li class="navbar-text m-lg-2 m-1">
                    <span>شنبه تا پنج شنبه : 8 تا 8 شب</span>
                    <img src="{{ asset('icons1/clock.png') }}">
                </li>
            </ul>
            <ul class="navbar-nav text-right" dir="rtl">
                <li class="nav-item m-lg-2 m-1"><a href="{{ route('home') }}" class="nav-link active">خانه</a></li>
                <li class="nav-item m-lg-2 m-1"><a href="#" class="nav-link">درباره ما</a></li>
                <li class="nav-item m-lg-2 m-1"><a href="{{ route('contact.create') }}" class="nav-link">تماس با ما</a></li>
                <li class="nav-item m-lg-2 m-1 d-md-none d-block">
                    @if(auth()->check())
                        <a href="{{ route(auth()->user()->isAdmin() ? 'admin.home' :'home') }}" class="nav-link">پنل کاربری</a>
                    @else
                        <a href="{{ route('join-member.view') }}" class="btn-custom">عضو شوید</a>
                        <a href="{{ route('login-member.view') }}" class="btn-custom">ورود</a>
                    @endif
                </li>
            </ul>
        </div>
    </div>

    {{--</div>--}}
</nav>