routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Morilog\Jalali\Jalalian;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('home');

Route::view('/about','about')->name('about');
Route::view('/health-news','health')->name('health.news');

Route::get('/download/voice',function (){
    return response()->download(base_path("about_corona_virus.mpeg"));
})->name('voice.download');

Route::get('/pdf/download',function (){
    return \Illuminate\Support\Facades\Response::download(base_path('corona_recommendation.pdf'));
})->name('pdf.download');

Route::prefix('admin')->name('admin.')->namespace('Auth')->group(function () {
    Route::get('home', 'AdminController@template')->name('home');
    Route::get('login', 'AdminController@showLoginForm')->name('login.view');
    Route::post('login/check', 'AdminController@check')->name('login.check');
    Route::post('logout', 'AdminController@logout')->name('logout');
    Route::get('users/notifications/markAsRead', 'AdminController@markAsRead')->name('users.notifications.markAsRead');
});

Route::prefix('user')->name('user.')->namespace('Auth')->group(function () {
    Route::get('round/{id}', 'UserController@index')->name('round');
    Route::get('join/{round}', 'UserController@create')->name('join');
    Route::get('login/{round?}', 'UserController@login')->name('login');
    Route::post('login/check/{round?}', 'UserController@check')->name('check');
    Route::get('panel', 'UserController@dashboard')->name('dashboard');
    Route::post('logout', 'UserController@logout')->name('logout');
    Route::post('pre/store/{id}', 'UserController@prestore')->name('prestore');
    Route::post('store/{id}', 'UserController@store')->name('store');
    Route::get('pay/start/{round}', 'UserController@pay')->name('pay.start');
    Route::get('pay/result', 'UserController@orderResult')->name('pay.result');
    Route::post('otp/send', 'UserController@otpSend')->name('otp.send');
    Route::post('otp/verify', 'UserController@otpVerify')->name('otp.verify');
    Route::get('all', 'UserController@all')->name('all');
});

Route::prefix('attachment')->name('attachment.')->group(function () {
    Route::post('store/{round_id}/{user_id}', 'AttachmentController@store')->name('store');
    Route::get('download/{round_id}/{user_id}', 'AttachmentController@download')->name('download');
    Route::put('update/{round_id}/{user_id}', 'AttachmentController@update')->name('update');
    Route::delete('destroy/{round_id}/{user_id}', 'AttachmentController@destroy')->name('destroy');
});

Route::delete('round/destroy/multiple', 'RoundController@destroyMultiple')->name('round.destroy.multiple');
Route::delete('round/users/destroy/multiple', 'RoundController@destroyMultiple')->name('round.users.destroy.multiple');
Route::resource('round', 'RoundController');

Route::get('price/set', function () {
    if (\App\Price::count() > 0) {
        $price = \App\Price::first()->price;
    } else {
        $price = null;
    }
    return view('price')->with([
        'price' => $price
    ]);
})->name('price.set')->middleware('auth:admin');
Route::post('price/change', function (\Illuminate\Http\Request $request) {
    \Illuminate\Support\Facades\Validator::make([$request], [
        'price' => 'required|numeric'
    ], [
        'price.required' => 'وارد کردن قیمت الزامی است',
        'price.numeric' => 'قیمت باید به صورت عددی باشد'
    ]);
    if (\App\Price::count() > 0) {
        $price = \App\Price::first();
        $price->price = $request->price;
        $price->save();
    } else {
        \App\Price::create([
            'price' => $request->price
        ]);
    }
    return redirect()->route('admin.home');
})->name('price.change')->middleware('auth:admin');

app/Round.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Round extends Model
{
    protected $fillable = [
       'date','start' , 'end' , 'capacity' , 'remaining'
    ];

    public function users(){
        return $this->belongsToMany(User::class , 'round_users');
    }
}

app/Http/Controllers/RoundController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RoundRequest;
use App\Round;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Morilog\Jalali\CalendarUtils;

class RoundController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rounds = Round::select('date', DB::raw('count(*) as total'))->groupBy('date')->orderBy('date', 'DESC')->get();
        return view('round.index')->with(compact('rounds'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('round.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  RoundRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(RoundRequest $request)
    {
        $data = $request->all();
        $data['remaining'] = $request->capacity;
        $data['date'] = CalendarUtils::createCarbonFromFormat('Y-m-d', $data['date'])->toDateString();
        Round::create($data);
        return redirect()->route('round.show', $data['date']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $rounds = Round::where('date', $id)->get();
        return view('round.indexpost')->with(compact('rounds'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $round = Round::find($id);
        return view('round.edit')
            ->with(compact('round'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  RoundRequest $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(RoundRequest $request, $id)
    {
        $data = $request->all();
        $r = Round::find($id);
        if ($data['capacity'] < $r->remaining ){
            $data['remaining'] = $data['capacity'];
        } else if ($data['capacity'] > $r->capacity) {
            $data['remaining'] = ($data['capacity'] - $r->capacity) + $r->remaining;
        }
        $data['date'] = CalendarUtils::createCarbonFromFormat('Y-m-d', $data['date'])->toDateString();
        $r->update($data);
        return redirect()->route('round.show', $r->date);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $round = Round::find($id);
        $round->delete();
        return redirect()->back();
    }

    public function destroyMultiple(Request $request)
    {
        $dates = $request->deletable;
        foreach ($dates as $date)
            Round::where('date', $date)->first()->delete();
    }
}

resources/views/round/create.blade.php
@extends('layouts.admin.template')

@section('title','ثبت سانس جدید')
<link type="text/css" rel="stylesheet" href="{{ asset('style/calendar.css') }}">
<link type="text/css" rel="stylesheet" href="{{ asset('style/wickedpicker.css') }}">
<style>
    label , input , input::placeholder{
        font-family: iransans_web_light;
    }
    .form-group{
        margin-bottom: 2rem !important;
    }

    .custom-error{
        text-align: right;
        direction: rtl;
        font-weight: bold;
        font-size: 12px;
        color : #b81212;
    }
</style>
@section('style')
@endsection

@section('content')
    <div class="col-md-7 col-sm-9 col-11 mx-auto">
        <div class="d-flex flex-row justify-content-between align-items-center">
            <a href="{{ route('round.index') }}" data-md-tooltip="بازگشت"
               class="shortcut-link shadow-sm material-icons md-tooltip md-tooltip--top">
                <img src="{{ asset('icons1/return.png') }}">
            </a>
            <h5 class="iransans-web-bold text-primary">
                ثبت سانس
            </h5>
        </div>
        <form method="post" action="{{ route('round.store') }}" class="form p-4 text-right bg-white" dir="rtl">
            {{ csrf_field() }}
            <div class="row">
                <div class="col-md-6 col-12 form-group">
                    <label for="date">برای تاریخ :</label>
                    <input type="text" id="date" name="date" class="form-control form-control-sm" value="{{ old('date') }}" autocomplete="off" placeholder="روز ثبت سانس" dir="rtl">
                    @if($errors->has('date'))
                        <p class="custom-error">{{ $errors->first('date') }}</p>
                    @endif
                </div>
                <div class="col-md-6 col-12 form-group">
                    <label for="start">شروع از :</label>
                    <input type="text" id="start" name="start" class="form-control form-control-sm" value="{{ old('start') }}" autocomplete="off"  placeholder="ساعت دقیق شروع نوبت" dir="rtl">
                    @if($errors->has('start'))
                        <p class="custom-error">{{ $errors->first('start') }}</p>
                    @endif
                </div>
                <div class="col-md-6 col-12 form-group">
                    <label for="end">ادامه تا :</label>
                    <input type="text" id="end" name="end" class="form-control form-control-sm" value="{{ old('end') }}" autocomplete="off"  dir="rtl" placeholder="ساعت دقیق اتمام نوبت">
                    @if($errors->has('end'))
                        <p class="custom-error">{{ $errors->first('end') }}</p>
                    @endif
                </div>
                <div class="col-md-6 col-12 form-group">
                    <label for="capacity">ظرفیت :</label>
                    <input type="number" id="capacity" name="capacity" class="form-control form-control-sm" value="{{ old('capacity') }}" autocomplete="off"  dir="rtl" placeholder="ظرفیت افراد آزمایش دهنده در نوبت">
                    @if($errors->has('capacity'))
                        <p class="custom-error">{{ $errors->first('capacity') }}</p>
                    @endif
                </div>
                <div class="col-12 form-group text-left">
                    <input type="submit" class="btn btn-danger rounded-0" value="ثبت">
                </div>
            </div>
        </form>
    </div>
@endsection

@section('script')
    <script src="{{ asset('js/wickedpicker.js') }}"></script>
    <script src="{{ asset('js/jalali.js') }}"></script>
    <script src="{{ asset('js/calendar.js') }}"></script>
    <script src="{{ asset('js/calendar-setup.js') }}"></script>
    <script src="{{ asset('js/calendar-fa.js') }}"></script>
    <script type="text/javascript">
        $("input[name='start'] , input[name='end']").wickedpicker({
            twentyFour: true,
            minutesInterval : 5,
            timeSeparator: ':',
        });
        Calendar.setup({
            inputField     :    "date",   // id of the input field
            button         :    "date",   // trigger for the calendar (button ID)
            ifFormat       :    "%Y-%m-%d",       // format of the input field
            dateType	   :	'jalali',
            weekNumbers    : false
        });
    </script>
@endsection

resources/views/round/edit.blade.php
@extends('layouts.admin.template')

@section('title','ویرایش سانس')
<link type="text/css" rel="stylesheet" href="{{ asset('style/calendar.css') }}">
<link type="text/css" rel="stylesheet" href="{{ asset('style/wickedpicker.css') }}">
<style>
    label , input , input::placeholder{
        font-family: iransans_web_light;
    }
    .form-group{
        margin-bottom: 2rem !important;
    }

    .custom-error{
        text-align: right;
        direction: rtl;
        font-weight: bold;
        font-size: 12px;
        color : #b81212;
    }
</style>
@section('style')
@endsection

@section('content')
    <div class="col-md-7 col-sm-9 col-11 mx-auto">
        <div class="d-flex flex-row justify-content-between align-items-center">
            <a href="{{ route('round.index') }}" data-md-tooltip="بازگشت"
               class="shortcut-link shadow-sm material-icons md-tooltip md-tooltip--top">
                <img src="{{ asset('icons1/return.png') }}">
            </a>
            <h5 class="iransans-web-bold text-primary">
                ویرایش سانس
            </h5>
        </div>
        <form method="post" action="{{ route('round.update',$round->id) }}" class="form p-4 text-right bg-white" dir="rtl">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <div class="row">
                <div class="col-md-6 col-12 form-group">
                    <label for="date">برای تاریخ :</label>
                    <input type="text" id="date" name="date" class="form-control form-control-sm" value="{{ old('date') ?: \Morilog\Jalali\CalendarUtils::strftime('Y-m-d',$round->date) }}" placeholder="روز ثبت سانس" dir="rtl">
                    @if($errors->has('date'))
                        <p class="custom-error">{{ $errors->first('date') }}</p>
                    @endif
                </div>
                <div class="col-md-6 col-12 form-group">
                    <label for="start">شروع از :</label>
                    <input type="text" id="start" name="start" class="form-control form-control-sm" value="{{ old('start') ?: $round->start}}" placeholder="ساعت دقیق شروع نوبت" dir="rtl">
                    @if($errors->has('start'))
                        <p class="custom-error">{{ $errors->first('start') }}</p>
                    @endif
                </div>
                <div class="col-md-6 col-12 form-group">
                    <label for="end">ادامه تا :</label>
                    <input type="text" id="end" name="end" class="form-control form-control-sm" value="{{ old('end') ?: $round->end }}" dir="rtl" placeholder="ساعت دقیق اتمام نوبت">
                    @if($errors->has('end'))
                        <p class="custom-error">{{ $errors->first('end') }}</p>
                    @endif
                </div>
                <div class="col-md-6 col-12 form-group">
                    <label for="capacity">ظرفیت :</label>
                    <input type="number" id="capacity" name="capacity" class="form-control form-control-sm" value="{{ old('capacity') ?: $round->capacity}}" dir="rtl" placeholder="ظرفیت افراد آزمایش دهنده در نوبت">
                    @if($errors->has('capacity'))
                        <p class="custom-error">{{ $errors->first('capacity') }}</p>
                    @endif
                </div>
                <div class="col-12 form-group text-left">
                    <input type="submit" class="btn btn-danger rounded-0" value="ویرایش">
                </div>
            </div>
        </form>
    </div>
@endsection

@section('script')
    <script src="{{ asset('js/wickedpicker.js') }}"></script>
    <script src="{{ asset('js/jalali.js') }}"></script>
    <script src="{{ asset('js/calendar.js') }}"></script>
    <script src="{{ asset('js/calendar-setup.js') }}"></script>
    <script src="{{ asset('js/calendar-fa.js') }}"></script>
    <script type="text/javascript">
        $("input[name='start']").wickedpicker({
            twentyFour: true,
            minutesInterval : 1,
            timeSeparator: ':',
            now : $("input[name='start']").val()
        });
        $("input[name='end']").wickedpicker({
            twentyFour: true,
            minutesInterval : 1,
            timeSeparator: ':',
            now : $("input[name='end']").val()
        });
        Calendar.setup({
            inputField     :    "date",   // id of the input field
            button         :    "date",   // trigger for the calendar (button ID)
            ifFormat       :    "%Y-%m-%d",       // format of the input field
            dateType	   :	'jalali',
            weekNumbers    : false
        });
    </script>
@endsection

resources/views/round/show.blade.php
{{ $round }}

resources/views/round/users.blade.php
@extends('layouts.admin.template')

@section('title','سانس ها')

@section('style')
    <link type="text/css" rel="stylesheet" href="{{ asset('style/index/flaticon.css') }}">
    <style>
        .table th {
            font-size: 13px;
        }

        .box {
            text-align: right;
            direction: rtl;
            border: 1px solid rgb(31, 186, 180);
            border-radius: 5px;
            line-height: 1.75;
            padding: .75rem;
            background-color: rgb(213, 251, 245);
            color: rgb(1, 104, 152);
            font-size: 14px;
            font-family: iransans_web;
            margin: 1rem 0;
        }

        .box-header, .box-header > div {
            display: flex;
            flex-direction: row;
            justify-content: flex-start;
            align-items: center;
            flex-wrap: wrap;
        }

        .box-divider {
            margin: 1rem 0;
            width: 100%;
            height: 1.5px;
            background-color: rgb(31, 186, 180);
        }
    </style>
@endsection

{{--@section('content')--}}
{{--<div class="col-md-11 col-12 text-right mx-auto">--}}
{{--<div class="d-flex flex-row justify-content-between">--}}
{{--<a href="{{ route('round.show',\App\Round::find($id)->date) }}" class="shortcut-link">--}}
{{--<img src="{{ asset('icons1/return.png') }}">--}}
{{--</a>--}}
{{--<h6 class="border-bottom border-info p-2 text-primary iransans-web-medium">--}}
{{--نوبت های رزرو شده برای تاریخ‌--}}
{{--<br>--}}
{{--<span dir="rtl">{{ toFaDigits(\Morilog\Jalali\Jalalian::forge(\App\Round::find($id)->date)->format('%d %B %y')) }}</span>--}}
{{--</h6>--}}
{{--</div>--}}
{{--<div class="d-flex flex-row flex-wrap justify-content-between">--}}
{{--@foreach($users as $user)--}}
{{--<div class="box col-md-3 col-sm-6 col-12">--}}
{{--<div class="box-header">--}}
{{--<div class="mx-2"> {{ $user->name }}</div>--}}
{{--<div class="mx-2">--}}
{{--<span class="flaticon flaticon-calendar-2 ml-1"></span>--}}
{{--<span>{{ toFaDigits(\Morilog\Jalali\Jalalian::forge($user->round->date)->format('%d %B %y')) }}</span>--}}
{{--</div>--}}
{{--<div class="mx-2">--}}
{{--<i class="flaticon flaticon-clock ml-1"></i>--}}
{{--<span>{{ toFaDigits($user->round->end.' - '.$user->round->start) }}</span>--}}
{{--</div>--}}
{{--<div class="mx-2">--}}
{{--<i class="flaticon flaticon-user ml-1"></i>--}}
{{--<span>{{ toFaDigits($user->parent) }}</span>--}}
{{--</div>--}}
{{--</div>--}}
{{--<div class="box-divider"></div>--}}
{{--<p class="mb-1">--}}
{{--<span class="font-weight-bold text-danger w-50"><span--}}
{{--class="flaticon flaticon-phone-receiver ml-1"></span>تماس</span>--}}
{{--<span class="text-dark">{{ toFaDigits($user->phone) }}</span>--}}
{{--</p>--}}
{{--<p class="mb-0">--}}
{{--<span class="font-weight-bold text-danger w-50"><span--}}
{{--class="flaticon flaticon-question ml-1"></span>سن</span>--}}
{{--<span class="text-dark mr-3">{{ toFaDigits($user->age) }}</span>--}}
{{--</p>--}}
{{--</div>--}}
{{--@endforeach--}}
{{--</div>--}}
{{--</div>--}}
{{--@endsection--}}


@section('content')
    @include('layouts.alert')

    <div class="col-12 mx-auto my-5 iransans-web-light text-right">
        <div class="d-flex flex-row justify-content-between align-items-end mb-md-4">
            <div>
                <a href="{{ route('round.show',$round->date) }}" class="shortcut-link">
                    <img src="{{ asset('icons1/return.png') }}" width="20" height="20">
                </a>
                <a href="{{ route('round.create') }}" class="btn btn-sm btn-primary px-4">
                    سانس جدید
                </a>
            </div>
            <div class="col-md-4 pr-0">
                <h5 class="mb-0">سانس <strong
                            style="font-size: 16px">({{toFaDigits(\Morilog\Jalali\Jalalian::forge($round->date)->format('%A, %d %B %y').', ساعت '.$round->end.' - '.$round->start)}}
                        )</strong></h5>
                {{--<div class="input-group input-group-sm rounded">--}}
                {{--<div class="input-group-append bg-white border border-right-0 rounded-left">--}}
                {{--<img src="{{ asset('icons1/search.png') }}" width="20" height="20" class="rounded mt-1 mx-1">--}}
                {{--</div>--}}
                {{--<input class="form-control border-left-0" type="search" placeholder="جست و جو" aria-label="Search"--}}
                {{--dir="rtl">--}}
                {{--</div>--}}
            </div>
        </div>
        @if(count($users))
            <table id="example1" class="table rounded bg-white text-dark rounded">
                <thead>
                <tr dir="rtl" class="ml-auto">
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0"></td>
                    <td class="border-0 d-flex align-items-center">
                        <input type="checkbox" class="toggle" value="1">
                        <span class="fas fa-chevron-down font-s font-weight-bold text-dark mr-2"
                              data-toggle="dropdown"></span>
                        <ul class="dropdown-menu dropdown-menu-right p-1 text-right">
                            <li>
                                <form id="round_multiple" method="post"
                                      action="{{ route('round.users.destroy.multiple') }}" class="d-none">
                                    {{ csrf_field() }}
                                    {{ method_field('delete') }}
                                </form>
                                <a onclick="$(this).addClass('active');$('.alert-container').fadeIn();"
                                   class="delete text-dark" href="#">حذف</a>
                            </li>
                        </ul>
                    </td>
                </tr>
                <tr class="bg-light">
                    <th class="p-2" style="width: 35px"></th>
                    <th class="p-2" style="width: 35px"></th>
                    <th class="p-2" style="width: 35px"></th>
                    <th class="p-2">نتیجه آزمایش</th>
                    <th class="p-2">آدرس</th>
                    <th class="p-2">سن</th>
                    <th class="p-2">کد ملی</th>
                    <th class="p-2">شماره تماس</th>
                    <th class="p-2">
                        <div class="d-flex justify-content-end align-items-center">
                            <span class="mr-1">نام پدر</span>
                            <span class="fas fa-sort text-lighter"></span>
                        </div>
                    </th>
                    <th class="p-2">
                        <div class="d-flex justify-content-end align-items-center">
                            <span class="mr-1">نام و نام خانوادگی</span>
                            <span class="fas fa-sort text-lighter"></span>
                        </div>
                    </th>
                    <th class="p-2"></th>
                </tr>
                </thead>
                <tbody>

                @php  $index=1; @endphp
                @foreach($users as $user)
                    <tr>
                        <td>
                            @if(\App\Attachment::where('round_id',$round->id)->where('user_id',$user->id)->count() > 0)
                                <form method="post" action="{{ route('attachment.destroy' , ['round_id' => $round->id , 'user_id' => $user->id]) }}" class="d-none">
                                    {{ csrf_field() }}
                                    {{ method_field('delete') }}
                                </form>
                            @endif
                            <a onclick="$(this).addClass('active');$('.alert-container').fadeIn();" href="#"
                               class="material-icons md-tooltip md-tooltip--top delete" data-md-tooltip="حذف نتیجه">
                                <img src="{{ asset('icons1/trash.png') }}" width="20" height="20">
                            </a></td>
                        <td>
                            <form method="post" action="{{ route('attachment.update',['round_id' => $round->id , 'user_id' => $user->id]) }}"
                                  enctype="multipart/form-data" class="d-none">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                <input type="file" name="file">
                            </form>
                            <a class="update material-icons md-tooltip md-tooltip--top" data-md-tooltip="ویرایش نتیجه">
                                <img src="{{ asset('icons1/edit.png') }}" width="20" height="20">
                            </a></td>
                        @if(\App\Attachment::where('round_id',$round->id)->where('user_id',$user->id)->first())
                            <td><a href="{{ route('attachment.download' , ['round_id' => $round->id , 'user_id' => $user->id]) }}"
                                   class="material-icons md-tooltip md-tooltip--top" data-md-tooltip="مشاهده نتیجه">
                                    <img src="{{ asset('icons1/eye.png') }}" width="20" height="20">
                                </a></td>
                        @else
                            <td>
                                <form method="post" action="{{ route('attachment.store',['round_id' => $round->id , 'user_id' => $user->id]) }}"
                                      enctype="multipart/form-data" class="d-none">
                                    {{ csrf_field() }}
                                    <input type="file" name="file">
                                </form>
                                <a class="upload material-icons md-tooltip md-tooltip--top"
                                   data-md-tooltip="آپلود نتیجه">
                                    <img src="{{ asset('icons1/upload.png') }}" width="20" height="20">
                                </a></td>
                        @endif
                        <td class="text-dark">
                            <span class="badge badge-{{ \App\Attachment::where('round_id',$round->id)->where('user_id',$user->id)->first() ? 'success' : 'warning' }}">{{ \App\Attachment::where('round_id',$round->id)->where('user_id',$user->id)->first() ? 'ارسال شده' : 'در انتظار' }}</span>
                        </td>
                        <td class="text-dark font-s">{{ toFaDigits($user->address) }}</td>
                        <td class="text-dark">{{ toFaDigits($user->age) }}</td>
                        <td class="text-dark">{{ toFaDigits($user->melli_code) }}</td>
                        <td class="text-dark">{{ toFaDigits($user->phone) }}</td>
                        <td class="text-dark" dir="rtl">{{ toFaDigits($user->parent) }}</td>
                        <td class="text-dark">{{ toFaDigits($user->name) }}</td>
                        <td style="width: 15px">
                            <input type="checkbox" name="deletable[]" value="{{ $user->id }}">
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <div class="alert alert-primary text-right my-3" dir="rtl">
این سانس توسط کسی رزرو نشده است.
            </div>
        @endif
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $("a.upload , a.update").on("click", function () {
                $(this).prev().find('input[type=\'file\']').click();
            });

            $("input[type='file']").on("change", function () {
                $(this).parent().submit();
            })
        });
    </script>
@endsection